Task1
thelonggoodbuy/picture_show pull request #1
Opened 2020-09-28 19:23 UTC by thelonggoodbuy

2020-09-28 19:58 UTC, Slawikus requested changes

2020-09-28 19:58 UTC, Slawikus commented on .vscode/settings.json
> +    "python.linting.enabled": false
Этого файла не должно быть в репозитории, всю эту папку надо удалить, закоммитеть удаление и добавить в гитигнор. Это локальные настройки, их не кладут в репозиторий.

2020-09-28 19:58 UTC, Slawikus commented on project/urls.py
>      path('admin/', admin.site.urls),
Эту строку можно убрать - мы не будем использовать Джанго админ. Все ручками писать будем

2020-09-28 19:58 UTC, Slawikus commented on templates/base.html
> +    <title>{% block title %}The last picture show{% endblock title %}</title>
У тебя ж сайт только для Киева, может не стоит писать все на английском языке в шаблонах ?

2020-09-28 19:58 UTC, Slawikus commented on users/models.py
> +class User(models.Model):
Смотри, лучше создать класс пользователя на основе уже готового класса AbstractUser Джанго - там уже все что надо есть и не стоит велосипед создавать. Глянь в книге, там все по шагам расписано как это сделать

2021-02-11 08:19 UTC, thelonggoodbuy commented on .vscode/settings.json
> +    "python.linting.enabled": false
Файл удален.

2021-02-11 08:19 UTC, thelonggoodbuy commented on project/urls.py
>      path('admin/', admin.site.urls),
Удалил строку

2021-02-11 08:21 UTC, thelonggoodbuy commented on templates/base.html
> +    <title>{% block title %}The last picture show{% endblock title %}</title>
Я сейчас пишу шаблоны и разботаю с Bootstap, ко второму таску все будет на украинском языке.

2021-02-11 08:21 UTC, thelonggoodbuy commented on users/models.py
> +class User(models.Model):
Модель пользователя на основе AbstractUser подготовлена.

2021-02-11 09:02 UTC, Slawikus commented on users/admin.py
> +class CustomUserAdmin(UserAdmin):
А зачем тебе эта админка?

2021-02-11 09:02 UTC, Slawikus commented on users/tests.py
> +        self.assertEqual(response.status_code, 200)
Вот это условие тестируется уже в предыдущем тесте - зачем его здесь повторять?

2021-02-11 09:02 UTC, Slawikus commented on users/tests.py
> +    username = 'newuser'
К слову - а разве пользователям юзернейм нужен в твоей системе? Мне кажется что просто мэйла будет им достаточно для идентификации в системе

2021-02-11 09:02 UTC, Slawikus commented on users/tests.py
> +    def test_signup_form(self):
Название теста не правильное - то что тестируется никакого отношения к форме сайнапа не имеет. По факту то что ты проверяешь - это если создать пользователя напрямую в базе данных то он реально создаётся в базе данных

2021-02-11 10:29 UTC, thelonggoodbuy commented
тестовый комментарий

2021-02-11 10:33 UTC, thelonggoodbuy commented
тестовый комментарий с кусочком кода
`class HomePageTest(SimpleTestCase):

    def test_home_page_status_code(self):
        response = self.client.get("/")
        self.assertEqual(response.status_code, 200)
`

2021-02-11 10:46 UTC, thelonggoodbuy commented
https://github.com/thelonggoodbuy/picture_show/blob/d472a29f8328d0ddfc602712e4ca7d169e299fbb/users/forms.py#L1-L12

2021-02-11 13:53 UTC, Slawikus commented on users/models.py
> +    pass
Вообще-то тут тоже надо убрать юзернейм если он совсем не будет использоваться. Вот почитай тут https://testdriven.io/blog/django-custom-user-model/

2021-02-11 13:53 UTC, Slawikus commented on users/forms.py
> +        exclude = ['username',]
А разве и fields и exclude можно одновременно использовать? Я думал либо то либо то

2021-02-14 09:18 UTC, Slawikus commented on templates/base.html
> +{% comment %} <!DOCTYPE html>
А что это за коммент тут наверху затесался?

2021-02-14 09:18 UTC, Slawikus commented on users/managers.py
> +class CustomUserManager(BaseUserManager):
А зачем ты этот мэнэджер определил? Он вроде ж ни чем не отличается от базового/встроенного.

2021-02-14 09:18 UTC, Slawikus commented on users/tests.py
> +        self.assertEqual(get_user_model().objects.all()[0].password, self.password)
Как мы обсудили этот момент проверить не выйдет

2021-02-14 09:18 UTC, Slawikus commented on users/tests.py
> +    def test_create_user(self, email, password, **extra_fields):
Что вот тут происходит что-то я не понимаю. Это просто код который ты забыл удалить?

2021-02-15 10:16 UTC, thelonggoodbuy commented on templates/base.html
> +{% comment %} <!DOCTYPE html>
забыл подчисть кусок закоменченого кода. Убираю.

2021-02-15 11:37 UTC, thelonggoodbuy commented on users/tests.py
> +    def test_create_user(self, email, password, **extra_fields):
Та да. я проверил весь код и почистил от комментариев. Впредь перед пушем, буду проверять не осталось ли каких то кусков кода спрятанных в коментарии, который стоит подчистить.

2021-02-15 16:49 UTC, Slawikus approved these changes

2021-02-16 07:33 UTC, merged